### ISSUE TITLE
Bug: chat overview handles return erroneous msg/mention counts

### ISSUE THREAD

**Issue by seanmc86** [worldr/server#27]
#### Summary
The Worldr client API getChannelsPersonal/getChannelsWork/getChannelsGlobal handles return different (erroneous) data to the Mmost API handles when it comes to msg/mention counts.

#### Steps to reproduce
On dev:
User id rj9nwdsctpgodj4hqbohxn8oqe
Channel id 8ckwcmmynpy59bq9e4begd81gc

From the client app, POST to /channels/members/{user_id}/view to clear all notifications for channel id 8ckwcmmynpy59bq9e4begd81gc

Then view the updated msg/mention counts via:
Mmost: ChannelsApi(client).usersUserIdChannelsChannelIdUnreadGet
Worldr: getChannelsPersonal

#### Expected behaviour
Worldr counts should match mmost counts.

#### Observed behaviour
The mmost handle correctly updates msg and mention counts to zero, worldr handles do not.

When using the mmost handle ChannelsApi(client).usersUserIdChannelsChannelIdUnreadGet
Response data:
ChannelUnread[teamId=, channelId=8ckwcmmynpy59bq9e4begd81gc, msgCount=0, mentionCount=0, ]

When using the worldr handles getChannelsPersonal etc
Response data:
ChannelInfo (ChannelInfo[id=8ckwcmmynpy59bq9e4begd81gc, members=2, msgCount=1, mentionCount=1, ])

**Comment by Aurora12** [comment]
Fixed by https://github.com/worldr/server/pull/29
