### ISSUE TITLE
Broken test due to new "kind" entry.

### ISSUE THREAD

**Issue by ygworldr** [worldr/server#4]
#### Summary

The test `testMaterializedPublicChannels` in `server/store` tests for odd edge cases. The new "kind" field breaks it. Note that the test is run from `server/store/sqlstore` but lives in `server/store/storetest/` for some reasons/..

#### Steps to reproduce

Look into the file, search for this bug number and uncomment everything.

Run `time richgo test ./...` and watch it fail.

#### Expected behaviour

The test pass.

#### Observed behaviour (that appears unintentional) 

The test does not pass.

#### Possible fixes

Well, I commented out the whole thing. It is probably not a good idea to have it there.

**Comment by ygworldr** [comment]
See `commit d2497670d` for details.

**Comment by Aurora12** [comment]
This must have been fixed already, wasn't it?
